/** @type {import('jest').Config} */
require("dotenv").config({ path: ".env" });

module.exports = {
  testEnvironment: "node",
  testMatch: [
    "**/__tests__/**/*.js",
    "**/tests/**/*.test.js",
    "**/tests/**/*.spec.js",
  ],
  testPathIgnorePatterns: [],
  verbose: true,
  forceExit: false,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: false,
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*.js"],
  coverageDirectory: "coverage",
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/tests/",
    "/__tests__/",
    "src/config/",
    "src/docs/",
    "src/middlewares/createFolder.js",
    "src/middlewares/abac.js",
    "src/middlewares/accessLog.js",
    "src/middlewares/auditLog.js",
    "src/middlewares/backup.js",
    "src/middlewares/dynamicAccess.js",
    "src/middlewares/tokenRateLimiter.js",
    "src/middlewares/activityLog.js",
    "src/middlewares/sessionCleanup.js",
    "src/utils/storagePath.js",
    "src/utils/upload.js",
    "src/utils/controllerWrapper.js",
    "src/routes/",
    "src/models/",
    "src/controllers/",
    "src/utils/seedMenuGroups.js",
    "src/utils/seedPermissions.js",
    "src/utils/generateSwagger.js",
    "src/utils/env.js",
    "src/utils/appPath.js",
    "src/services/redis.service.js",
    "src/services/tenant.service.js",
    "src/services/session.service.js",
    "src/services/auth.service.js",
    "src/services/user.service.js",
    "src/services/tenantBackup.service.js",
    "src/services/emailQueue.service.js",
    "src/services/rateLimiter.service.js",
    "src/services/roles.service.js",
    "src/services/migration.service.js",
  ],
  coverageThreshold: {
    global: {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  transform: {},
  transformIgnorePatterns: ["/node_modules/"],
  moduleNameMapper: {
    "^uuid$": "<rootDir>/__mocks__/uuid.js",
  },
  moduleFileExtensions: ["js", "json"],
  testTimeout: 10000,
};
