const role = require("./roleConstants");
const app = require("./appConstants");
const permission = require("./permissionConstants");

module.exports = {
  // Role constants
  SUPER_ADMIN_ROLE_ID: role.SUPER_ADMIN_ROLE_ID,
  ROLE_NAMES: role.ROLE_NAMES,
  ROLE_IDS: role.ROLE_IDS,
  ROLE_LEVELS: role.ROLE_LEVELS,
  BUILTIN_ROLES: role.BUILTIN_ROLES,
  ROLE_PERMISSIONS: role.ROLE_PERMISSIONS,
  MENU_SLUGS: role.MENU_SLUGS,
  PERMISSION_TYPES: role.PERMISSION_TYPES,
  ROLE_MENU_ASSIGNMENTS: role.ROLE_MENU_ASSIGNMENTS,
  // Permission constants
  USER_PERMISSIONS: permission.USER_PERMISSIONS,
  TENANT_PERMISSIONS: permission.TENANT_PERMISSIONS,
  ROLE_PERMISSION_CATEGORIES: permission.ROLE_PERMISSION_CATEGORIES,
  // App constants
  DEFAULT_PAGE: app.DEFAULT_PAGE,
  DEFAULT_LIMIT: app.DEFAULT_LIMIT,
  MAX_LIMIT: app.MAX_LIMIT,
  USER_STATUS: app.USER_STATUS,
  OTP_LENGTH: app.OTP_LENGTH,
  OTP_EXPIRY_MINUTES: app.OTP_EXPIRY_MINUTES,
  OTP_MAX_REQUESTS: app.OTP_MAX_REQUESTS,
  OTP_REQUEST_WINDOW_MINUTES: app.OTP_REQUEST_WINDOW_MINUTES,
  PASSWORD_MIN_LENGTH: app.PASSWORD_MIN_LENGTH,
  PASSWORD_SALT_ROUNDS: app.PASSWORD_SALT_ROUNDS,
  DEFAULT_SESSION_EXPIRY_HOURS: app.DEFAULT_SESSION_EXPIRY_HOURS,
  MAX_SESSIONS_PER_USER: app.MAX_SESSIONS_PER_USER,
  DEFAULT_BACKUP_RETENTION_DAYS: app.DEFAULT_BACKUP_RETENTION_DAYS,
  MAX_BACKUP_RETENTION_DAYS: app.MAX_BACKUP_RETENTION_DAYS,
  BACKUP_DIR: app.BACKUP_DIR,
};
